import os
import subprocess

RRD_DIR = "rrd"
GRAPH_DIR = "static/graphs"

os.makedirs(RRD_DIR, exist_ok=True)
os.makedirs(GRAPH_DIR, exist_ok=True)


# ----------------------------------------------------
# Helpers
# ----------------------------------------------------

def sanitize(interface):
    return interface.replace("/", "_").replace(" ", "_")


def rrd_path(interface):
    return os.path.join(
        RRD_DIR,
        sanitize(interface) + ".rrd"
    )


def graph_path(interface, period):
    return os.path.join(
        GRAPH_DIR,
        f"{sanitize(interface)}_{period}.png"
    )


# ----------------------------------------------------
# Create RRD
# ----------------------------------------------------

def ensure_rrd(interface):

    filename = rrd_path(interface)

    if os.path.exists(filename):
        return

    subprocess.run([

        "rrdtool",
        "create",
        filename,

        "--step", "30",

        "DS:rx:GAUGE:90:0:U",
        "DS:tx:GAUGE:90:0:U",

        # 24 hours
        "RRA:AVERAGE:0.5:1:2880",
        "RRA:MAX:0.5:1:2880",

        # 7 days
        "RRA:AVERAGE:0.5:10:1008",
        "RRA:MAX:0.5:10:1008",

        # 30 days
        "RRA:AVERAGE:0.5:60:720",
        "RRA:MAX:0.5:60:720",

        # 1 year
        "RRA:AVERAGE:0.5:1440:366",
        "RRA:MAX:0.5:1440:366"

    ], check=True)

    print(f"[RRD] Created {filename}")


# ----------------------------------------------------
# Update RRD
# ----------------------------------------------------

def update_rrd(interface, rx, tx):

    ensure_rrd(interface)

    subprocess.run([

        "rrdtool",
        "update",
        rrd_path(interface),
        f"N:{rx}:{tx}"

    ], check=True)


# ----------------------------------------------------
# Generate Graph
# ----------------------------------------------------

def generate_graph(interface, period="24h"):

    ensure_rrd(interface)

    PERIODS = {

        "1h": "-1h",
        "24h": "-24h",
        "7d": "-7d",
        "30d": "-30d",
        "1y": "-1y"

    }

    start = PERIODS.get(period, "-24h")

    rrd = rrd_path(interface)

    output = graph_path(interface, period)

    cmd = [

        "rrdtool",
        "graph",
        output,

        "--start", start,
        "--end", "now",

        "--width", "900",
        "--height", "280",

        "--title", f"{interface} Traffic",

        "--vertical-label", "Mbps",

        "--lower-limit", "0",

        "--alt-autoscale-max",

        "--slope-mode",

        "--rigid",

        "--font", "DEFAULT:10:",

        "--color", "BACK#FFFFFF",
        "--color", "CANVAS#FFFFFF",
        "--color", "GRID#DDDDDD",
        "--color", "MGRID#AAAAAA",
        "--color", "FONT#000000",

        f"DEF:rx={rrd}:rx:AVERAGE",
        f"DEF:tx={rrd}:tx:AVERAGE",

        "CDEF:neg_tx=tx,-1,*",

        "AREA:rx#66CC66:Inbound",
        "LINE2:rx#008800",

        "AREA:neg_tx#6699FF:Outbound",
        "LINE2:neg_tx#0033CC",

        "COMMENT:\\n",

        "GPRINT:rx:LAST:RX Current\\:%8.2lf Mbps",
        "GPRINT:rx:AVERAGE:Avg\\:%8.2lf",
        "GPRINT:rx:MAX:Max\\:%8.2lf\\n",

        "GPRINT:tx:LAST:TX Current\\:%8.2lf Mbps",
        "GPRINT:tx:AVERAGE:Avg\\:%8.2lf",
        "GPRINT:tx:MAX:Max\\:%8.2lf\\n",

        "COMMENT:Generated by Huawei NMS"

    ]

    subprocess.run(cmd, check=True)

    return output


# ----------------------------------------------------

if __name__ == "__main__":

    update_rrd("GE0/0/22", 5.2, 2.8)

    print(generate_graph("GE0/0/22", "24h"))
